[package]
name = "hyperlane-sealevel-recipient-echo"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = { version = "=1.14.3", path = "/Users/steven/code/eclipse-labs/eclipse/sdk/program" }
hyperlane-sealevel-mailbox = { path = "../../mailbox", features = ["no-entrypoint"] }

[lib]
crate-type = ["cdylib", "lib"]
