[package]
name = "hyperlane-sealevel"
version = "0.1.0"
edition = "2021"

[dependencies]
# fuels = "0.33" FIXME remove
hyperlane-core = { path = "../../hyperlane-core" }
async-trait = { version = "0.1", default-features = false }
thiserror = "1.0"
serde = "1.0"
anyhow = "1.0"
tracing-futures = "0.2"
tracing = "0.1"

# FIXME remove
# [build-dependencies]
# abigen = { path = "../../utils/abigen", features = ["fuels"] }
